services:
  web:
    image: fisai-gym-web:current
    mem_limit: 128m
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
  api:
    mem_limit: 384m
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
